# tmux configuration file
source-file $XDG_CONFIG_HOME/tmux/config/options/keybindings.conf
source-file $XDG_CONFIG_HOME/tmux/config/options/options.conf

# ===============================================
# plugins (must be at the end of tmux.conf)
# ===============================================
# TMUX plugin manager path
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.local/share/tmux/plugins'
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# powerline plugin
set -g @plugin 'erikw/tmux-powerline'

# tree plugin
source-file $XDG_CONFIG_HOME/tmux/config/plugins/treemux.conf
set -g @plugin 'kiyoon/treemux'

# smark window naming plugin
source-file $XDG_CONFIG_HOME/tmux/config/plugins/tmux-window-name.conf
set -g @plugin 'ofirgall/tmux-window-name'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.local/share/tmux/plugins/tpm/tpm'
