# use vim key bindings in copy mode
set-option -g mode-keys vi

# set pane border color
set-option -g pane-active-border-style "fg=brightgreen"
set-option -g pane-border-style        "fg=brightblack"

# set status-left to show session name and prefix status
# set-option -g status-left-length 40
# set-option -g status-left "[#S] prefix:'#{prefix}' "

# set status-right to show date and time, and prefix status (from tmux-prefix-highlight plugin)
# set-option -g status-right "#{prefix_highlight} | %a %Y/%m/%d %H:%M"

# set status-middle to show current window name
# set-option -g window-status-format        " #I:#W#{?window_flags, #{window_flags}, } "
# set-option -g window-status-style         "bg=default,fg=colour240"
# set-option -g window-status-current-style "bg=colour245,fg=black,bold"
