name: Build
on:
  push:
    branches:
      - main
    paths:
      - '**.nix'
      - 'flake.lock'
  pull_request:
    paths:
      - '**.nix'
      - 'flake.lock'
  workflow_dispatch:
jobs:
  # build-nixos:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 120
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
  #       with:
  #         persist-credentials: false
  #     - name: Setup Nix
  #       uses: ./.github/actions/setup-nix
  #       with:
  #         cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
  #     - name: Build NixOS configuration
  #       run: nix build --show-trace --no-link .#nixosConfigurations.nixos.config.system.build.toplevel
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - name: Setup Nix
        uses: ./.github/actions/setup-nix
        with:
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build home-manager configuration
        run: nix build --show-trace --no-link .#homeConfigurations.wsl.activationPackage
  # build-mac:
  #   runs-on: macos-latest
  #   timeout-minutes: 120
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
  #       with:
  #         persist-credentials: false
  #     - name: Setup Nix
  #       uses: ./.github/actions/setup-nix
  #       with:
  #         cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
  #     - name: Build nix-darwin configuration
  #       run: nix build --show-trace --no-link .#darwinConfigurations.mac.system
